# Generated by Django 4.2.4 on 2023-11-15 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='popularity',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_path',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
